### ISSUE TITLE
Error starting grafana bridge v7.1.0

### ISSUE THREAD

**Issue by Helene** [IBM/ibm-spectrum-scale-bridge-for-grafana#133]
**Describe the bug**
Grafana-bridge v7.1.0 runs in the following error during the start
```
# python3 zimonGrafanaIntf.py -c 10
Traceback (most recent call last):
  File "zimonGrafanaIntf.py", line 37, in <module>
    from opentsdb import OpenTsdbApi
  File "/root/ibm-spectrum-scale-bridge-for-grafana/source/opentsdb.py", line 27, in <module>
    from collector import SensorCollector, QueryPolicy
  File "/root/ibm-spectrum-scale-bridge-for-grafana/source/collector.py", line 121, in <module>
    class SensorTimeSeries(object):
  File "/root/ibm-spectrum-scale-bridge-for-grafana/source/collector.py", line 153, in SensorTimeSeries
    def _setup_static_metrics_data(self, metric_names: list[str]):
TypeError: 'type' object is not subscriptable
```

**To Reproduce**
1. Cone the repository `# git clone https://github.com/IBM/ibm-spectrum-scale-bridge-for-grafana.git bridge-71`
2. Switch to branch v7.1 `git switch v7.1`
3. Start bridge `python3 zimonGrafanaIntf.py -c 10`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - IBM Storage Scale system type:
    - [ ] IBM Storage Scale classic cluster.
    - [ ] IBM Storage Scale Container Native Storage Access (CNSA).
    - [x] IBM Elastic Storage Server (ESS).
 - IBM Storage Scale cluster version: 5.1.8.1
 - IBM Storage Scale bridge for Grafana version: v7.1.0
 - Grafana version: 9.5
 - OS Grafana is installed on: RHEL85

**Additional context**

**Comment by Helene** [comment]
The system on which the error occurred is running python3.6. 
The root cause of the problem described [here](https://stackoverflow.com/questions/63460126/typeerror-type-object-is-not-subscriptable-in-a-function-signature).
The grafana-bridge default python version is 3.9 and have been not tested with 3.6. 
```
[root@fscc-sr650-49 source]# python3 version
python3: can't open file 'version': [Errno 2] No such file or directory
[root@fscc-sr650-49 source]# python3
Python 3.6.8 (default, Jan 14 2022, 11:04:20)
[GCC 8.5.0 20210514 (Red Hat 8.5.0-7)] on linux
```
