### ISSUE TITLE
Grafana Dashboard shows HTTP 500 Error by using grafana bridge with CNSA 5.1.5 prerelease version

### ISSUE THREAD

**Issue by Helene** [IBM/ibm-spectrum-scale-bridge-for-grafana#68]
**Describe the bug**
GrafanaBridge pods are successfully deployed and are in running state. Never less the metric graph in Grafana Dashboard shows HTTP500 error

**Expected behavior**
the metric graph should show data

**Desktop (please complete the following information):**
 - IBM Spectrum Scale system type:
    - [ ] IBM Spectrum Scale classic cluster.
    - [X] IBM Spectrum Scale Container Native Storage Access (CNSA).
    - [ ] IBM Elastic Storage Server (ESS).
 - IBM Spectrum Scale cluster version: 5.1.5
 - IBM Spectrum Scale bridge for Grafana version: 7.0.6
 - Grafana version: 7.5.16
 - OS Grafana is installed on: OCP 4.10

**Additional context**
[root@myocp ~]# oc rsh ibm-spectrum-scale-grafana-bridge-6844d54c6-cwf6f
Defaulted container "grafanabridge" out of: grafanabridge, initservice (init)
sh-4.4$ cd /var/log/ibm_bridge_for_grafana/
sh-4.4$ ls
cherrypy_access.log  cherrypy_error.log
sh-4.4$ cat cherrypy_access.log
10.254.21.111 - - [21/Sep/2022:10:36:53] "POST /api/query HTTP/1.1" 500 824 "" "Grafana/7.5.16"
10.254.21.111 - - [21/Sep/2022:10:36:56] "POST /api/query HTTP/1.1" 500 824 "" "Grafana/7.5.16"
10.254.21.111 - - [21/Sep/2022:10:37:00] "POST /api/query HTTP/1.1" 500 824 "" "Grafana/7.5.16"
10.254.21.111 - - [21/Sep/2022:10:37:01] "POST /api/query HTTP/1.1" 500 824 "" "Grafana/7.5.16"
10.254.21.111 - - [21/Sep/2022:10:37:06] "POST /api/query HTTP/1.1" 500 824 "" "Grafana/7.5.16"
10.254.21.111 - - [21/Sep/2022:10:37:11] "POST /api/query HTTP/1.1" 500 824 "" "Grafana/7.5.16"
10.254.21.111 - - [21/Sep/2022:10:37:16] "POST /api/query HTTP/1.1" 500 824 "" "Grafana/7.5.16"
10.254.21.111 - - [21/Sep/2022:10:37:21] "POST /api/query HTTP/1.1" 500 824 "" "Grafana/7.5.16"
10.254.21.111 - - [21/Sep/2022:10:37:26] "POST /api/query HTTP/1.1" 500 824 "" "Grafana/7.5.16"
10.254.21.111 - - [21/Sep/2022:10:37:31] "POST /api/query HTTP/1.1" 500 824 "" "Grafana/7.5.16"
10.254.21.111 - - [21/Sep/2022:10:37:36] "POST /api/query HTTP/1.1" 500 824 "" "Grafana/7.5.16"
10.254.21.111 - - [21/Sep/2022:10:37:41] "POST /api/query HTTP/1.1" 500 824 "" "Grafana/7.5.16"
10.254.21.111 - - [21/Sep/2022:10:37:46] "POST /api/query HTTP/1.1" 500 824 "" "Grafana/7.5.16"
10.254.21.111 - - [21/Sep/2022:10:37:51] "POST /api/query HTTP/1.1" 500 824 "" "Grafana/7.5.16"
10.254.21.111 - - [21/Sep/2022:10:38:44] "POST /api/query HTTP/1.1" 500 824 "" "Grafana/7.5.16"
10.254.21.111 - - [21/Sep/2022:10:41:04] "POST /api/query HTTP/1.1" 500 824 "" "Grafana/7.5.16"
10.254.21.111 - - [21/Sep/2022:10:41:27] "POST /api/query HTTP/1.1" 500 824 "" "Grafana/7.5.16"
10.254.21.111 - - [21/Sep/2022:10:41:28] "POST /api/query HTTP/1.1" 500 824 "" "Grafana/7.5.16"
10.254.21.111 - - [21/Sep/2022:10:41:33] "POST /api/query HTTP/1.1" 500 824 "" "Grafana/7.5.16"
sh-4.4$ cat cherrypy_error.log
[21/Sep/2022:10:35:29] ENGINE Bus STARTING
[21/Sep/2022:10:35:29] ENGINE Started monitor thread 'Autoreloader'.
[21/Sep/2022:10:35:29] ENGINE Serving on https://0.0.0.0:8443/
[21/Sep/2022:10:35:29] ENGINE Bus STARTED
[21/Sep/2022:10:36:53] HTTP
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cherrypy/lib/jsontools.py", line 59, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "zimonGrafanaIntf.py", line 460, in POST
    query, dsOp, dsInterval = self._createZimonQuery(q, jreq.get('start'), jreq.get('end'))
  File "zimonGrafanaIntf.py", line 354, in _createZimonQuery
    bucketSize = self._getSensorPeriod(inMetric)
  File "zimonGrafanaIntf.py", line 434, in _getSensorPeriod
    if sensorAttr['name'] == str('\"%s\"' % sensor):
KeyError: 'name'

**Comment by Helene** [comment]
resolved with #69
